[package]
name = "a_star_pathfinder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
nalgebra = "0.32.3"
egui = "0.24.1"
eframe = "0.24.1"
epi = "0.17.0"
